Some additions, styling, formatting, and minor spelling fixes
AMD-Lab/R-Kurs-Buch pull request #33
Opened 2022-10-18 12:03 UTC by wh64

2022-10-18 12:26 UTC, JoseAlanis commented
This PR relates to #31, thanks @wh64

2022-10-19 06:47 UTC, JoseAlanis requested changes
Some minor comments and requests. Thanks for all the work, looks nice.

2022-10-19 06:47 UTC, JoseAlanis commented on chapters/00-Einfuehrung.Rmd
> +(3 + 2) * 5
Thanks for adding the spaces. It's something we talked about in the beginnings of the book but we still have multiple inconsistencies across chapters. There are other "operations" of this kind in the book. Would you mind going through the chapters to fixing this?

2022-10-19 06:47 UTC, JoseAlanis commented on chapters/01-Erste_Schritte.Rmd
>  x*y
This one for instance

2022-10-19 06:47 UTC, JoseAlanis commented on chapters/01-Erste_Schritte.Rmd
>  z <- x*10
And this one, and so on

2022-10-19 06:47 UTC, JoseAlanis commented on chapters/02-Datenstruktur.Rmd
> +Rechts oben im Fenster ist das `Environment`-tab. Hier sieht man alle im `global Workspace` definierten Objekte (Datenstrukturen: Werte, Vektoren, Matrizen, Arrays, Listen, `data.frames`, `tibbles`;
Should we use a different term (i.e., not "tab")? I'm being picky here but some might get confused because it not what they would see as a "tab".

2022-10-19 17:15 UTC, wh64 commented
I went over everything again and tried to make things more consistent. Happy merging! 😉

2022-10-19 20:26 UTC, JoseAlanis approved these changes
Looks good; thanks for the edits 😄

2022-10-19 20:27 UTC, JoseAlanis approved these changes

2022-10-19 20:29 UTC, merged

2022-10-19 20:29 UTC, JoseAlanis commented
Thx @wh64.